#!/usr/bin/env python
import sys
import shutil

if len(sys.argv) < 3 or sys.argv[1] not in ["up", "out"]:
    sys.stderr.write("Usage: \n")
    sys.stderr.write("\tdotroll out <username>\n")
    sys.stderr.write("\tdotroll up <username>\n")
    sys.exit(1)

mode = sys.argv[1]

homedir = "/home/%s" % sys.argv[2]
git_repo = "git/dotfiles"
dotfiles = (
    ".bashrc",
    ".bash_profile",
    ".gitconfig"
)

for dfile in dotfiles:
    source = "%s/%s" % (homedir, dfile)
    destination = "%s/%s/%s" % (homedir, git_repo, dfile)

    if mode == 'out':
        source, destination = destination, source

    print "Copying '%s' to '%s'..." % (source, destination)
    shutil.copy(source, destination)
